# Numpy

### By Alka Pandey

Note: In Python, 1D numpy array are equivalent to vectors and 2D arrays are equivalent to matrices

In [11]:
# Import the numpy package
import numpy as np

In [100]:
# Check the numpy version
print(np.__version__)

'2.3.5'

In [12]:
# Create a 1 Dimensional numpy array from a list

list1 = [2,4,6,7,8]
arr1 = np.array(list1)
print(arr1)

[2 4 6 7 8]


In [15]:
type(arr1)

numpy.ndarray

In [13]:
# Create a 1 Dimensional numpy array from a tuple

tuple1 = (2,4,6,7,8)
arr2 = np.array(tuple1)
print(arr2)

[2 4 6 7 8]


In [16]:
type(arr2)

numpy.ndarray

In [14]:
# Create a 1 Dimensional numpy array from a set

set1 = {2,2,2,4,6,7,8}
arr3 = np.array(set1) #No error but not recommended because set is unordered/unindexed and usage will pe problematic later
print(arr3)

{2, 4, 6, 7, 8}


In [17]:
type(arr3)

numpy.ndarray

In [19]:
print(arr1[0])

2


In [20]:
print(arr2[0])

2


In [21]:
print(arr3[0]) #Throws an error because array was created from a set and set is unindexed/unordred

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [43]:
print(arr1)

[2 4 6 7 8]


In [23]:
type(arr1[0]) #Numpy arrays are homegeneous, all elements will be of same data type

numpy.int64

#### Demonstration below to show homogeneous element of numpy arrays when mixed type is given:

In [25]:
# Create a 1 Dimensional numpy array from with mixed type of elements and then check the type

list2 = [2.9,4,6,7,8.5]
arr4 = np.array(list2)
print(arr4)

[2.9 4.  6.  7.  8.5]


In [26]:
type(arr4) #Check type of array created

numpy.ndarray

In [44]:
type(arr4[3]) #Check the data type of elements, everything is converted to float which is a higher type so as to avoid loss of information

numpy.float64

In [31]:
# Another example of array where a string is present, entire nparray elements are converted to string type
list3 = [2,4,6,7,8,"Alka"]
arr5 = np.array(list3)
print(arr5)

['2' '4' '6' '7' '8' 'Alka']


In [33]:
print(type(arr5[0])) #Every element becomes a string because array is homegeneous

<class 'numpy.str_'>


#### Creating a multi-dimensional (2 dimensional) nparray:

In [35]:
aa1 = np.array([[1,3,8],[4,5,7]])
print(aa1)

[[1 3 8]
 [4 5 7]]


#### Creating a numpy array using np.ones function which assigns 1.0 to every element 

In [37]:
z1 = np.ones(5)
print(z1)

[1. 1. 1. 1. 1.]


In [39]:
z1_int = z1.astype(int) #Converting a np.ones generated array from float type to int type
print(z1_int)

[1 1 1 1 1]


In [40]:
z2 = np.ones((3,3)) #creating a 3*3 nparray from np.ones
print(z2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
ar1 = np.zeros(7) #creating a 1D nparray from np.zeros
print(ar1)

[0. 0. 0. 0. 0. 0. 0.]


In [42]:
ar2 = np.zeros((7,7)) #creating a 2D nparray from np.zeros with 7 rows and 7 columns
print(ar2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [49]:
# Using np.arange 

# syntax: np.arange(start,end,step optional)

c1 = np.arange(3,18)
print(c1)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [50]:
#array created with np.arange with a step size of 2
c2 = np.arange(3,18,2) 
print(c2)

[ 3  5  7  9 11 13 15 17]


### Attributes of Numpy arrays: shape,ndim,dtype,size

In [52]:
z1.shape #shape tells about row and column data

(5,)

In [53]:
ar2.shape

(7, 7)

In [54]:
z1.ndim #ndim tells about number of dimensions

1

In [55]:
ar2.ndim

2

In [56]:
z1.size # size helps you to look at number of elements

5

In [57]:
ar2.size

49

## Indexing in numpy array - starts with 0

##### Syntax: array[start:end index(exclusive):step(Optional)]

In [102]:
print(c2[1]) #Access element in the first index location

5


In [103]:
print(c2[2:5]) #Access element from 2nd index until 5th index but excluding the 5th index

[ 7  9 11]


### Slicing in numpy arrays:

Syntax: array[Rows that you want,Columns that you want]

Row Format: [start:end:step] <br>
Column format: [start:end:step]

In [58]:
nn1 = np.array([[2,5,6,7,8],[2,9,1,3,4]])
nn1

array([[2, 5, 6, 7, 8],
       [2, 9, 1, 3, 4]])

In [59]:
nn1[0:2,2:4] #array of rows,column. Return 0th and 1st Row, 2nd and 3rd columns

array([[6, 7],
       [1, 3]])

In [60]:
nn1[:,2:4] #Another way of writing/slicing

array([[7, 8],
       [3, 4]])

In [66]:
nn1[:,2:6] #another example

array([[6, 7],
       [1, 3]])

### View and Copy in numpy arrays.

###### View will sahre the memory with original array, Copy creates a separate memory block

In [70]:
nn1_copy1 = nn1
print(nn1_copy1)

[[2 5 6 7 8]
 [2 9 1 3 4]]


In [71]:
nn1_copy2 = np.copy(nn1)
print(nn1_copy2)

[[2 5 6 7 8]
 [2 9 1 3 4]]


In [73]:
nn1 = np.arange(10,15)
print(nn1)

[10 11 12 13 14]


In [74]:
nn1_copy1

array([[2, 5, 6, 7, 8],
       [2, 9, 1, 3, 4]])

In [75]:
nn1_copy2

array([[2, 5, 6, 7, 8],
       [2, 9, 1, 3, 4]])

In [105]:
v = nn1.view()
print(v)

[10 11 12 13 14]


In [107]:
print(v[0]) #access first element of the view

10


In [108]:
v[0] = 999 # Changing the element in the view to check if changes reflected in original or not
print(v)

[999  11  12  13  14]


In [109]:
nn1 #Original array also changed with changes made in view because they share memory

array([999,  11,  12,  13,  14])

### Insert an element in a certain index position in an array

In [76]:
arr = nn1
print(arr)

[10 11 12 13 14]


In [78]:
arrr = np.insert(arr,2,9999)
arrr

array([  10,   11, 9999,   12,   13,   14])

### np.linspace : Divides the sequence from the start till the end to give "n" equally spaced partitions

syntax: np.linspace(start range,end_range,number of elements you want-"n")

In [85]:
ls = np.linspace(0,100,5) #returns 5 equally spaced numbers between 0 and 100
print(ls)

[  0.  25.  50.  75. 100.]


### Type conversion in numpy arrays:

In [88]:
x = [22,44,66]
aaa = np.asarray(x) #converts a list to a numpy array - similar output to np.array
print(aaa)

[22 44 66]


In [87]:
type(aaa)

numpy.ndarray

### Reshaping the array - 1D to 2D and vice versa

Note: Needs to have same number of elements and should be logical

In [98]:
arrzero = np.zeros(9)
arrzero

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
arrshaped = arrzero.reshape((3,3))
arrshaped

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
arrshaped.ravel() #Ravel function is used to convert any dimension to 1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Data Type Optimization

In [110]:
a1 = np.array([1,2,3,4,5,6,7,77])
print(a1)

[ 1  2  3  4  5  6  7 77]


In [112]:
a1.dtype #default is integer 64 bits

dtype('int64')

In [113]:
# If you want to optimize the array a1

a1_optimized = np.array([1,2,3,4,5,6,7,77],dtype=np.int8)
print(a1_optimized)
print(a1_optimized.dtype)

[ 1  2  3  4  5  6  7 77]
int8


## Vector Operations in Python

#### Numpy is very good at mathematical operations and element wise operations

In [115]:
v1 = np.array([1,3,5])
v2 = np.array([12,32,56])

In [116]:
# Addition - element wise:

sum_vector = v1+v2
print(sum_vector)

[13 35 61]


In [118]:
# substraction

sub_vector = v2-v1
print(sub_vector)

[11 29 51]


In [119]:
# multiplication

mult_vector = v2*v1
print(mult_vector)

[ 12  96 280]


In [120]:
# Multiplication by scaler
c = 10

vec = c*v1
print(vec)

[10 30 50]


In [121]:
# Addition of a scaler
c = 10

vec2 = c+v1
print(vec2)

[11 13 15]


In [122]:
#comparison

v1>v2

array([False, False, False])

In [127]:
# dot product of matrices

matrix1 = np.array([[2,3],[4,5]])
matrix2 = np.array([[4,5],[1,1]])

matmul1 = np.dot(matrix1,matrix2) #Option 1

matmul2 = matrix1 @ matrix2 #Option 2

In [128]:
print(matmul1)

[[11 13]
 [21 25]]


In [129]:
print(matmul2)

[[11 13]
 [21 25]]


In [131]:
print(np.linalg.norm(v1)) #magnitude of vector

5.916079783099616


## Math functions in numpy

In [139]:
# Import math module

import math

In [132]:
# absolute

abs(-100)

100

In [133]:
# Rounding

round(6.89)

7

In [134]:
# min

min(3,4,5,61,1,9)

1

In [135]:
#sum function:

sum([7,4,3,2,22,2,1])

41

In [140]:
#square root

math.sqrt(16)

4.0

In [142]:
# trigonometric functions like sin,cos,tan

math.cos(0)

1.0

In [143]:
#pi

math.pi

3.141592653589793

### Statistical functions like mean, median, standard deviation

In [145]:
print(np.mean(v1))

3.0


In [146]:
print(np.median(v1))

3.0


In [147]:
print(np.var(v1))

2.6666666666666665


In [148]:
print(np.std(v1))

1.632993161855452


In [149]:
print(np.min(v1))

1


In [150]:
print(np.max(v1))

5


In [151]:
print(np.log(1))

0.0
